# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0002_auto_20160420_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
