# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0007_auto_20160426_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
