# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0008_auto_20160426_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='test.png', upload_to='media'),
            preserve_default=False,
        ),
    ]
