# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='/media/'),
        ),
    ]
