# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0010_auto_20160426_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
    ]
