# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0011_auto_20160426_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
