# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0012_auto_20160426_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
