# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0014_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
