# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wbp_app', '0015_auto_20160501_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('leader', models.CharField(max_length=30)),
                ('lecture_date', models.DateField()),
                ('lecture_start_time', models.TimeField()),
                ('lecture_end_time', models.TimeField()),
                ('moodle_link', models.URLField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
