# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0016_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateField()),
                ('lecture_start_time', models.TimeField()),
                ('lecture_end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='lecture_date',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lecture_end_time',
        ),
        migrations.RemoveField(
            model_name='module',
            name='lecture_start_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbp_app.Module'),
        ),
    ]
