# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0017_auto_20160502_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_date', models.DateField()),
                ('tutorial_start_time', models.TimeField()),
                ('tutorials_end_time', models.TimeField()),
                ('tutorial_group', models.CharField(max_length=2)),
                ('tutorial_location', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wbp_app.Module')),
            ],
        ),
    ]
