# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbp_app', '0020_tutorial_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_location',
            field=models.CharField(default='FakeRoom', max_length=100),
            preserve_default=False,
        ),
    ]
